version: '3.8'

services:
  pgadmin:
    depends_on: 
      - postgresql
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - TZ=Europe/Bucharest
      - PGADMIN_DEFAULT_EMAIL=admin@admin.admin
      - PGADMIN_DEFAULT_PASSWORD=student
    user: root
    ports: 
      - "8888:80"
    volumes: 
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - supermarket_network

  postgresql:
    image: postgres:latest
    env_file: .env
    ports: 
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes: 
      - postgres-db:/var/lib/postgresql/data
      - ./database/init/schema.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - supermarket_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U student -d supermarket"]
      interval: 5s
      timeout: 5s
      retries: 10
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - postgresql
    networks:
      - supermarket_network
  
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    networks:
      - supermarket_network
    restart: always

  auth_service:
    build: ./auth-service/
    ports:
      - "5005:5005"
    depends_on:
      - postgresql
    networks:
      - supermarket_network
  
  bussines_logic_service:
    build: ./business-logic-service/
    ports:
      - "5000:5000"
    depends_on:
      - postgresql
    networks:
      - supermarket_network

  database_api_service:
    build: ./database-api-service/
    ports:
      - "5010:5010"
    depends_on:
      - postgresql
    networks:
      - supermarket_network

volumes:
  postgres-db:
  pgadmin-data:
  grafana-data:
  portainer-data:

networks:
  supermarket_network: